### ISSUE TITLE
Raspberry pi resources

### ISSUE THREAD

**Issue by Matthewmads** [drewgates/learn_iot#2]
> These guys have a bunch of good resources for pi's, The MQTT tutorial is pretty basic but explains setting up a broker simply enough. They also have some cool stuff for running SQL, Tensor flow and others, all on a pi. 

https://pimylifeup.com/raspberry-pi-mosquitto-mqtt-server/
https://pimylifeup.com/category/projects/iot/

**Comment by drewgates** [comment]
Thanks Matt! I added your link to the `mosquitto` tutorial, as well as a link to a tutorial for AWS IoT Core. I've tinkered with `mosquitto` in the past, though I've recently been using the AWS solution for the promise of higher reliability. In the interest of focus on IoT rather than system administration, I'd recommend the AWS solution, but there's definitely a balance to be struck between reliability, cost, and security.
